apiVersion: v1
kind: Service
metadata:
  name: db-srv
spec:
  #type: LoadBalancer
  #externalTrafficPolicy: Local
  selector:
    app: db-deploy
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
