apiVersion: v1
kind: Service
metadata:
  name: backend-srv
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Local
  selector:
    app: backend-deploy-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010
