AWSTemplateFormatVersion: '2010-09-09'
Description: AWS ECS Saple Cluster IAM

Resources:
  MyEcsSampleAppECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement: 
          - Effect: Allow
            Principal: 
              Service: [ecs-tasks.amazonaws.com]
            Action: ['sts:AssumeRole']   
      Policies:
        - PolicyName: MyEcsSampleAppExecutionRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action: 
                    - 'ecr:GetAuthorizationToken'
                    - 'ecr:BatchCheckLayerAvailability'
                    - 'ecr:GetDownloadUrlForLayer'
                    - 'ecr:BatchGetImage'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                  Resource: "*"

Outputs:
  MyEcsSampleAppECSExecutionRole:
    Description: MyEcsSampleApp ECS Execution Role
    Value: !GetAtt 'MyEcsSampleAppECSExecutionRole.Arn'
    Export: 
      Name: MyEcsSampleAppECSExecutionRole
      